CC=g++

all: MultipleLinearRegression

knn: MultipleLinearRegression.cpp
	$(CC) MultipleLinearRegression.cpp -o MultipleLinearRegression

run: MultipleLinearRegression
	./MultipleLinearRegression

clean:
	rm -f *o
