CC=g++

all: ClassificationRegressionTrees

ClassificationRegressionTrees: ClassificationRegressionTrees.cpp
	$(CC) ClassificationRegressionTrees.cpp -o ClassificationRegressionTrees

run: ClassificationRegressionTrees
	./ClassificationRegressionTrees

clean:
	rm -f *.o
